### ISSUE TITLE
Support for CSS modules

### ISSUE THREAD

**Issue by clintharris** [Place1/parcel-plugin-typed-css-modules#1]
This plugin is exactly what I was looking for--thanks. That said, I'm having a problem with how the variable names are generated. Example:

**Input**
```css
/* styles.css */
.foo {
  font-weight: bold;
}
```
**Output**
```typescript
// styles.css.d.ts
export const fooV4p4513: string;
```

Any ideas? I'm using Parcel 1.9.7, TypeScript 3.0.1, and the following `tsconfig.json` file:
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "jsx": "react"
}
```

**Comment by Place1** [comment]
Interesting. Can you tell me what you eat after running typed css modules
directly from the CLI?
https://github.com/Quramy/typed-css-modules

**Comment by clintharris** [comment]
Ah, of course: it's because I have post-css configured to use CSS modules for "localized" classnames (per the [Parcel docs](https://parceljs.org/transforms.html#postcss):

```json
// .postcssrc
{
  "modules": true
  }
}
```

So `parcel-plugin-typed-css-modules` is getting CSS _after_ the classnames have been mangled by`postcss-modules`.

**Comment by Place1** [comment]
interesting. I have `modules: true` in the example within this repo and there doesn't seem to be an issue.

**Comment by hannupekka** [comment]
I'm having the same issue.

**Comment by hasparus** [comment]
Same problem here.

**Comment by clintharris** [comment]
@Place1 can you publish v1.1.0 (which fixes this issue) to npm?

**Comment by Place1** [comment]
@clintharris done! sorry for taking so long!

**Comment by garthenweb** [comment]
For me, the fix described here was not working using Parcel v1.11.0 (not sure if it's about the version), it sill outputted the generated classes and not the original class name.

I actually found out and tested this plugin as I was about to publish my own implementation, I didn't realize that something already existed before. As the implementation are similar but still not compatible I thought its fair to publish an alternative: [parcel-plugin-css-modules-type-generator](https://www.npmjs.com/package/parcel-plugin-css-modules-type-generator).

But I still wanted to comment in case you are interested in fixing the issue. As I had an implementation that was working for me, I didn't dig deeper into the issue, but I guess it's about the regex to identify the class names. In case you like to have more details, please let me know!

**Comment by Place1** [comment]
Hey I’d love to accept a PR fixing the issue if you know how.
